EncounterManager
Icewav3/TacticalGS3 pull request #19
Opened 2024-11-22 22:18 UTC by Spike-Zbb

2024-11-22 22:36 UTC, caterunions requested changes
requesting changes on the access level of some variables, and naming conventions to match the code currently in the project.

2024-11-22 22:36 UTC, caterunions commented on Assets/Scripts/EncounterScripts/EncounterManager.cs
> +	public void OnEncounterComplete(EncounterOutcome outcome)
is encounter outcome as an enum necessary? i feel like "bool victory" would accomplish the same thing as we're never gonna have a third outcome

2024-11-22 22:36 UTC, caterunions commented on Assets/Scripts/EncounterScripts/Encounter.cs
> +	public GameObject[] enemyGroup;
serialize private versions of these and expose read-only public ones

2024-11-22 22:36 UTC, caterunions commented on Assets/Scripts/EncounterScripts/TileEncounterTrigger.cs
> +	private EncounterManager encounterManager;
make encounter private and serialize it for the inspector, also follow variable naming conventions:
private -> _variable
public -> Variable

2024-11-22 22:36 UTC, caterunions commented on Assets/Scripts/EncounterScripts/TileEncounterTrigger.cs
> +		encounterManager = FindObjectOfType<EncounterManager>();
serialize a reference to encounter manager if possible, avoid find

2024-11-22 22:36 UTC, caterunions commented on Assets/Scripts/EncounterScripts/Encounter.cs
> +	public string id;
id is never used, and also should ideally be stored as something other than a string (if we need it...? unsure of its purpose)

2024-11-24 00:29 UTC, Icewav3 commented
@Spike-Zbb waiting on your response

2024-11-24 02:19 UTC, Spike-Zbb commented
Hi Cole, sorry, I just got home. I have already finished editing it. Do you want me to upload it now?

________________________________
发件人: Cole Dorman ***@***.***>
发送时间: 2024年11月23日 18:29
收件人: Icewav3/TacticalGS3 ***@***.***>
抄送: Yuhang Zhang ***@***.***>; Mention ***@***.***>
主题: Re: [Icewav3/TacticalGS3] EncounterManager (PR #19)


CAUTION: This email originates from outside RRC. Please verify the sender and always use caution with any requests, links or attached documents.


@Spike-Zbb<https://github.com/Spike-Zbb> waiting on your response

―
Reply to this email directly, view it on GitHub<https://github.com/Icewav3/TacticalGS3/pull/19#issuecomment-2495717590>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BLI3OO24635EJKROATYVAKL2CEMWNAVCNFSM6AAAAABSKIWKZOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOJVG4YTONJZGA>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-11-24 02:24 UTC, Spike-Zbb commented
I uploaded the latest changes

2024-11-24 14:51 UTC, caterunions approved these changes

2024-11-24 14:51 UTC, caterunions commented
All the changes look great, thanks!

2024-11-24 22:15 UTC, Icewav3 requested changes

2024-11-24 22:15 UTC, Icewav3 commented on Assets/Scripts/EncounterScripts/Encounter.cs
> +		Debug.Log("StartEncounter");
Use the sceneGod for this
example:  SceneGod.SInstance.EnterCombatState(enemyGroup);

2024-11-24 22:15 UTC, Icewav3 commented on Assets/Scripts/EncounterScripts/EncounterManager.cs
> +public class EncounterManager : MonoBehaviour
not sure if we can really utilize this class to its potential, as most of its functionality is in the sceneGod. Maybe just call thigns in the TileEncounterTrigger

2024-11-24 22:15 UTC, Icewav3 commented on Assets/Scripts/EncounterScripts/TileEncounterTrigger.cs
> +	private Encounter _encounter;
this should probably be enemyGroup

2024-11-24 22:15 UTC, Icewav3 commented on Assets/Scripts/EncounterScripts/TileEncounterTrigger.cs
> +public class TileEncounterTrigger : MonoBehaviour
I think encounter can be safely merged into this without causing problems

2024-11-25 05:03 UTC, Spike-Zbb commented
I re-modified the code according to Cole's suggestion, but I am not sure whether the _**SceneGod.SInstance.EnterCombatState(enemyGroup)**_ method needs parameters.

2024-11-26 03:37 UTC, Spike-Zbb commented
What does LevelEncounters do? When should I call the method in this ScriptableObject?

2024-11-26 15:15 UTC, merged