merge Encounter manager
Icewav3/TacticalGS3 pull request #23
Opened 2024-11-26 19:41 UTC by Spike-Zbb

2024-11-27 15:01 UTC, caterunions submitted a review, later dismissed

2024-11-27 15:09 UTC, caterunions requested changes
add player check to tile encounter trigger

2024-11-27 15:09 UTC, caterunions commented on Assets/Scripts/EncounterScripts/TileEncounterTrigger.cs
>  	{
this should check that the player is the one triggering it, not just any collision

2024-11-27 15:12 UTC, AlexQuennelle requested changes
Please fix code formatting with visual studio code cleanup

2024-11-27 15:12 UTC, AlexQuennelle commented on Assets/Scripts/EncounterScripts/LevelEncounters.cs
> +	private List<Encounter> levelEncounters;
Follow naming convention

2024-11-30 23:25 UTC, AlexQuennelle commented on Assets/Scripts/EncounterScripts/EncounterManager.cs
> +	private void Awake()
Why is this being called in Awake?

2024-12-01 04:29 UTC, AlexQuennelle approved these changes

2024-12-01 04:30 UTC, caterunions approved these changes

2024-12-01 04:47 UTC, merged